name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-24.04
    if: github.actor != 'github-classroom[bot]'
    steps:
    # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup ROS 2 Jazzy Environment
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      # 3. Run the Grader
      - name: ROS2 Publisher Test
        id: ros-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "Publisher Node Check"
          setup-command: "chmod +x .github/scripts/grade.sh"
          command: "bash .github/scripts/grade.sh"
          timeout: 10
          max-score: 100  
      
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ROS-TEST_RESULTS: "${{ steps.ros-test.outputs.result }}"
        with:
          runners: ros-test
